### PR TITLE
Fuzz only supported functions

### PR DESCRIPTION
**Pull request by FabrizioSandri**
The goal of this pull request is to fix the issue that has been discovered when using RcppDeepState to analyze the binsegRcpp package.

I discovered that if there is at least one function that cannot be analyzed, that is, a function whose arguments differ from the supported one, RcppDeepState terminates.

Fixes one of the problems found in the pull request [Check rcppdeepstate #13](https://github.com/tdhock/binsegRcpp/pull/13)

### CODE REVIEW

**Comment by tdhock** [comment]
can you please add a test case? maybe the easiest would be to just add a function with an unsupported type to the TestSAN package?

**Comment by FabrizioSandri** [comment]
@tdhock  In the most recent commits I have added a new function to the testSAN package, that takes as input a parameter that isn't allowed(`Rcpp::LogicalVector`).
```c++
// [[Rcpp::export]]
int unsupported_datatype(Rcpp::LogicalVector param){
  return param.size();
} 
```
I just renamed the existing `tests/testthat/test-debug-symbols.R` file to `tests/testthat/test-testSAN.R` rather than creating a new test file. This test file simply analyzes the testSAN package and determines whether any issues have been found. It has been proved locally that RcppDeepState detects some issues when using the supplied seed number, therefore if no errors are found, something went wrong.  

CI will take some time because of the other checks.

**Comment by tdhock** [comment]
great

**Comment by FabrizioSandri** [comment]
According to the new function that was added to the testSAN package, I had to update the tests. All of the checks are now successful.

**Pull request merged**
